config/routes.rb
Rails.application.routes.draw do

  resources :media_libraries, only: [:index, :create, :new]

  resources :movie_libraries, only: [:show] do
    resources :movies, only: [:show]
  end

  resources :tv_libraries, only: [:show]
  resources :tv_shows, only: [:show]
  resources :tv_seasons, only: [:show]
  resources :tv_episodes, only: [:show]
  
  

end

app/models/media_library.rb
class MediaLibrary < ActiveRecord::Base
  has_many :media_files, dependent: :destroy

  before_validation :strip_spaces
  before_validation :make_path_real

  after_create :scan
  
  validates :name, :path, presence: true, uniqueness: true
  validates :path, uniqueness: true
  validate :path_is_a_directory
  validate :path_is_absolute
  validates :type, presence: true, inclusion: %w(MovieLibrary TvLibrary)


  def scan
    checksums_in_library = self.media_files.all.each_with_object({}) do |media_file, hash|
      hash[media_file.checksum] = {id: media_file.id, status: media_file.status, library_path: media_file.path, paths: []}
    end
    media_files_to_save = {}
    
    Dir.glob(File.join(path, "**", "*")).each do |filename|
      extname = File.extname(filename)
      next unless MediaFile::MEDIA_EXTENSIONS.include?(extname.downcase)
      media_file = MediaFile.new(path: filename, name: File.basename(filename, extname))

      if !checksums_in_library[media_file.checksum]
        media_files_to_save[media_file.checksum] = media_file
      else
        if checksums_in_library[media_file.checksum][:status] == MediaFile::STATUS_MISSING
          missing_media_file = self.media_files.find(checksums_in_library[media_file.checksum][:id])
          missing_media_file.path = media_file.path
          missing_media_file.status = MediaFile::STATUS_ENABLED
          media_files_to_save[media_file.checksum] = missing_media_file
        else
          checksums_in_library[media_file.checksum][:paths] << media_file.path
        end
      end
    end

    media_files_to_save.values.each do |media_file|
      media_file = self.media_files.build(media_file.attributes) if media_file.new_record?
        
      if media_file.save
        checksums_in_library[media_file.checksum]||= {id: media_file.id, status: media_file.status, library_path: media_file.path, paths: []}
        checksums_in_library[media_file.checksum][:paths] << media_file.path
      else
        logger.error("File not imported: #{media_file.path}")
      end
    end

    checksums_in_library.each do |checksum, info|
      if info[:paths].empty?
        media_file = self.media_files.find(info[:id])
        media_file.mark_missing
      elsif !info[:paths].include?(info[:library_path])
        media_file = self.media_files.find(info[:id])
        media_file.path = info[:paths].last
        unless media_file.save
          logger.error("File not updated(path): #{media_file.path}")
        end
      end
    end
    self.scanned_at = Time.now
    save

    after_scan
  end


  
  private
  def make_path_real
    self.path = File.realpath(path) if !path.blank? && path.match(/^\//) && File.directory?(path)
  end

  def strip_spaces
    self.name = self.name.strip if self.name
    self.path = self.path.strip if self.path
  end

  def path_is_absolute
    if !path || !path.match(/^\//)
      errors.add(:path, "must be an absolute path")
    end
  end
  
  def path_is_a_directory
    if !path || !File.directory?(path)
      errors.add(:path, "must be a directory")
    end
  end
  
end

app/controllers/media_libraries_controller.rb
class MediaLibrariesController < ApplicationController
  def index
    @media_libraries = MediaLibrary.all
  end

  def new
    @media_library = MediaLibrary.new
  end

  def create
    if params[:media_library][:type]=="MovieLibrary"
      @media_library = MovieLibrary.new(params.require(:media_library).permit(:name, :path))
    elsif params[:media_library][:type]=="TvLibrary"
      @media_library = TvLibrary.new(params.require(:media_library).permit(:name, :path))
    else
      raise "Unsupported type"
    end
    if @media_library.save
      if @media_library.is_a?(MovieLibrary)
        redirect_to movie_library_path(@media_library)
      elsif @media_library.is_a?(TvLibrary)
        redirect_to tv_library_path(@media_library)
      else
        raise "Unsupported type"
      end
    else
      render "new"
      return
    end
  end
end

app/helpers/media_libraries_helper.rb
module MediaLibrariesHelper
end

app/views/media_libraries/_form.html.erb
<%= form_for @media_library, url: media_libraries_path(@media_library) do |f| %>
  <div class="form-group">
    <%= f.label :type %> :
    <%= f.select :type, options_for_select([["Movies", "MovieLibrary"], ["Television", "TvLibrary"]]), {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name %> :
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :path %> :
    <%= f.text_field :path, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/media_libraries/index.html.erb
<div class="container">
  <h1>Your Libraries</h1>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Path</th>
      <th>Last Scanned</th>
    </tr>
    <%= render @media_libraries %>
  </table>
  
  <br />
  <%= link_to "Add a new library", new_media_library_path, class: "btn btn-default" %>
</div>

app/views/media_libraries/new.html.erb
<div class="container">
  <h1>Add a new library</h1>
  <%= render "form" %>
  
  <br />
  <%= link_to "All libraries", media_libraries_path %>
</div>

app/views/media_libraries/show.html.erb
<div class="container">
  <h1><%= @media_library.name %></h1>
  <table class="table">
    <%= render @media_library.media_files %>
  </table>

  <br />
  <%= link_to "All libraries", media_libraries_path %>
</div>